version: 0.2

env:
  variables:
    ECR_REPO_URI: "<your-ecr-repo-uri>"  # Replace with your ECR repository URI

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - python3.8 -m pip install --upgrade pip
      - pip3 install flask

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t $ECR_REPO_URI:latest .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPO_URI:latest
