version: 0.2

phases:
  pre_build:
    commands:
      - env
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI:latest .
      - docker push $ECR_REPO_URI:latest
